# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "ldap"
    server.vm.hostname = "server"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "ldap"
    client.vm.hostname = "client"
  end

end
